### ISSUE TITLE
Feature request: Create App for Homey

### ISSUE THREAD

**Issue by L3nny5** [bang-olufsen/bang_olufsen-hacs#17]
Hey,

this is not really an issue, but I have no idea where I can post this request. If you have a better place, please do tell!

I love what you can do with this integration in Home Assistant. However I'm not very happy with Home Assistant. I think it is very illogical and is not very user friendly at all. The list is long, what I dislike about Home Assistant. However Home Assistant has a huge community and therefore a lot of integrations. 
Another nice product on the market is Homey which can also be extended with so called Apps. More info on the [Dev Site](https://tools.developer.homey.app/).

Is anything planned about creating such an App to integrate the B&O Mozart platform with Homey?

Lenny

**Comment by mj23000** [comment]
There are currently no plans to support Homey.

Kind regards
