### ISSUE TITLE
Volume entity not working anymore

### ISSUE THREAD

**Issue by Jydepotte** [bang-olufsen/bang_olufsen-hacs#21]
Hi,

Noticed that the sensor.beosound_volume entity does not work correctly anymore with my Beosound Theatre. Not sure whether this is related to the new firmware (3.4.1.8) on the Beosound, Home Assistant 2024.3.3 or the Bang & Olufsen integration.

You can still set the volume using the slider but the sensor.beosound_volume entity does not change.

I have scripts to change the volume up/down that does also not work anymore because they depend on the current volume level to work.

Kind regards

/Jan Lebeck

**Comment by Jydepotte** [comment]
Example of a script to change the volume down by 5:

service: media_player.volume_set
target:
  entity_id: media_player.beosound_theatre_36199013_3
data:
  volume_level: >-
    {{ states.media_player.beosound_theatre_36199013_3.attributes.volume_level - 0.05 }}

**Comment by Jydepotte** [comment]
![Volume](https://github.com/bang-olufsen/bang_olufsen-hacs/assets/145715005/846ac2d9-be09-4f7f-a819-1f9caca18618)
Never changes...

**Comment by Jydepotte** [comment]
Have checked on a completely fresh installation of Home Assistant also - same problem.

**Comment by mj23000** [comment]
I'm guessing that you have tried rebooting the Theatre. 

What version of this integration are you using? If it is 2.1.1, can you try downgrading to 2.0.0? 
And are any other WebSocket notifications working?, for example does changing source change artwork and metadata as expected?

Kind regards

**Comment by Jydepotte** [comment]
After downloading everything works... tried to upgrade to 2.1.1 again - then NOT working again. Going back to 2.0.0. Repeated this a few times to verify. 1.8.1 also works.

**Comment by mj23000** [comment]
Ok. I have not been able to replicate this issue with WebSocket notifications on 2.1+, but you are the second one reporting problems. The issue seems to be the new WebSocket backend for the API client. I'll try to revert to the old backend and release a new version tomorrow.

**Comment by mj23000** [comment]
Can you try updating to 2.1.3?

**Comment by Jydepotte** [comment]
Hi ... just upgraded and tested... and it now works as usual on 2.1.3.

**Comment by mj23000** [comment]
Good. I'll stay with the old WebSocket backend.
