### ISSUE TITLE
Restart?

### ISSUE THREAD

**Issue by lundgreen-jyskebank-dk** [bang-olufsen/bang_olufsen-hacs#23]
Hi. I've got a usecase where I would like to restart my devices (e.g my beolab 28's). Is this possible via the api?

**Comment by mj23000** [comment]
This is currently not possible to do with the API. Why would you want to restart your devices?

**Comment by lundgreen-jyskebank-dk** [comment]
Well. It is actually a workaround. Once in a while my speakers drops multiroom or the music gets out of sync. A restart normally fixes this. I wished my speakers where hard wired but they all sit on a TP-link Mesh network (Deco XE75's). I know that the rootcause may be the mesh but a nightly restart could prehaps make me happier. By the way - does B&O have some kind of detailed whitepaper for optimal wireless network settings? And question two: How does the mobile app restart the devices (in the ui: support -> setup -> device -> restart). Is there a websocket call I can trigger.

Kind regards
Frank

**Comment by mj23000** [comment]
Sorry to hear that you are having issues. It seems that at this point wireless mesh setups aren't as reliable as normal wireless setups. I'm not familiar with any Beolink documentation.

The app uses the REST API but the restart endpoint is not available in the API specification that we provide to the public. I'll see what I can do. The WebSocket part of the API is only for communication of the current state of the device, so no commands can be sent to the device through the WebSocket.

**Comment by lundgreen-jyskebank-dk** [comment]
Yep. Let's close this issue.

Sounds great if you would consider restart in the api. Some crazy customers, like me, might consider a scheduled restart at 04 AM 🤗

**Comment by mj23000** [comment]
Reboot has been added as an action to [2.4.0](https://github.com/bang-olufsen/bang_olufsen-hacs/releases/tag/2.4.0). 
Hopefully this will make your Beolink setup more stable, though this should not be considered a long-term fix for any Beolink issues.

Kind regards,
Markus

**Comment by lundgreen-jyskebank-dk** [comment]
Great Markus. I'll try not to misuse the reboot feature 🤗 Eager to try it out when a release drops. Thanks!
