### ISSUE TITLE
Overlay service is gone from one of my HA. After update 2.5.2

### ISSUE THREAD

**Issue by JAFC-BandO** [bang-olufsen/bang_olufsen-hacs#24]
I can no longer find overlay service on one of my HA setups after updating to 2.5.2.

![image](https://github.com/user-attachments/assets/b73b616f-3d5c-4baa-af80-7f493441a057)
Using this :
Core
2024.10.1
Supervisor
2024.09.1
Operating System
13.1

**Comment by mj23000** [comment]
The overlay service has been replaced by the `play_media` service's `announce` parameter. There is documentation for use in the [README](https://github.com/bang-olufsen/bang_olufsen-hacs/blob/main/README.md)
