### ISSUE TITLE
Configuration Error

### ISSUE THREAD

**Issue by Danlymp** [bang-olufsen/bang_olufsen-hacs#25]
Hi! Since the update my devices are showing an Error. All of them Beolab 8/ Level/ Balance. They are being discovered normally. Maybe you can assist. Thanks

![IMG_0487](https://github.com/user-attachments/assets/a7b19821-e621-4455-931d-8e204eedea8a)
![IMG_0488](https://github.com/user-attachments/assets/759f35fe-948c-4862-bd8b-5ca21173e8b2)

**Comment by mj23000** [comment]
Sorry about that. It should be fixed now in [2.5.3](https://github.com/bang-olufsen/bang_olufsen-hacs/releases/tag/2.5.3)

**Comment by Danlymp** [comment]
Great thanks!
